// ─────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/generate-registry.mjs — do not edit by hand.
// Run:  npm run generate:registry
// Generated: 2026-07-24T21:10:50.710Z
// 7 brands · 77 models · 233 variants
// ─────────────────────────────────────────────────────────────────────

/* ── Types ─────────────────────────────────────────────────────────── */

export type CarVariant = {
  /** Unique id, e.g. "ferrari-f40--1987-ferrari-f40" */
  id: string;
  /** Display name, e.g. "1987 Ferrari F40" */
  name: string;
  /** Year extracted from filename, or null */
  year: number | null;
  /** Path to the GLB under public/, e.g. "/models/ferrari/F40/1987_ferrari_f40.glb" */
  url: string;
};

export type CarModel = {
  /** Unique id, e.g. "ferrari-f40" */
  id: string;
  /** Model display name, e.g. "F40" */
  name: string;
  /** Brand slug, e.g. "ferrari" */
  brandId: string;
  /** Id of the "base" variant (plain factory version) — used by quiz + museum
   *  hero. Chosen by heuristic, overridable via src/lib/base-variants.json. */
  baseVariantId: string;
  /** All available GLB variants (editions, years, tuners, etc.) */
  variants: CarVariant[];
};

export type Brand = {
  /** Slug, e.g. "ferrari" */
  id: string;
  /** Display name, e.g. "Ferrari" */
  name: string;
  /** All models for this brand, sorted alphabetically */
  models: CarModel[];
};

/* ── Registry ──────────────────────────────────────────────────────── */

export const BRANDS: Brand[] = [
  {
    "id": "bugatti",
    "name": "Bugatti",
    "models": [
      {
        "id": "bugatti-chiron",
        "name": "Chiron",
        "brandId": "bugatti",
        "baseVariantId": "bugatti-chiron--free-bugatti-chiron",
        "variants": [
          {
            "id": "bugatti-chiron--free-bugatti-chiron",
            "name": "Free Bugatti Chiron",
            "year": null,
            "url": "/models/bugatti/free_bugatti_chiron.glb"
          }
        ]
      },
      {
        "id": "bugatti-eb110",
        "name": "EB110",
        "brandId": "bugatti",
        "baseVariantId": "bugatti-eb110--bugatti-eb110",
        "variants": [
          {
            "id": "bugatti-eb110--bugatti-eb110",
            "name": "Bugatti EB110",
            "year": null,
            "url": "/models/bugatti/bugatti_eb110.glb"
          }
        ]
      },
      {
        "id": "bugatti-eb110-ss-roadcar",
        "name": "EB110 SS Roadcar",
        "brandId": "bugatti",
        "baseVariantId": "bugatti-eb110-ss-roadcar--bugatti-eb110-ss-roadcar",
        "variants": [
          {
            "id": "bugatti-eb110-ss-roadcar--bugatti-eb110-ss-roadcar",
            "name": "Bugatti EB110 SS Roadcar",
            "year": null,
            "url": "/models/bugatti/bugatti_eb110_ss_roadcar.glb"
          }
        ]
      },
      {
        "id": "bugatti-la-voiture-noire",
        "name": "LA Voiture Noire",
        "brandId": "bugatti",
        "baseVariantId": "bugatti-la-voiture-noire--2019-bugatti-la-voiture-noire",
        "variants": [
          {
            "id": "bugatti-la-voiture-noire--2019-bugatti-la-voiture-noire",
            "name": "2019 Bugatti LA Voiture Noire",
            "year": 2019,
            "url": "/models/bugatti/2019_bugatti_la_voiture_noire.glb"
          }
        ]
      },
      {
        "id": "bugatti-mistral",
        "name": "Mistral",
        "brandId": "bugatti",
        "baseVariantId": "bugatti-mistral--2024-bugatti-mistral",
        "variants": [
          {
            "id": "bugatti-mistral--2024-bugatti-mistral",
            "name": "2024 Bugatti Mistral",
            "year": 2024,
            "url": "/models/bugatti/2024_bugatti_mistral.glb"
          }
        ]
      },
      {
        "id": "bugatti-tourbillon",
        "name": "Tourbillon",
        "brandId": "bugatti",
        "baseVariantId": "bugatti-tourbillon--2026-bugatti-tourbillon",
        "variants": [
          {
            "id": "bugatti-tourbillon--2026-bugatti-tourbillon",
            "name": "2026 Bugatti Tourbillon",
            "year": 2026,
            "url": "/models/bugatti/2026_bugatti_tourbillon.glb"
          }
        ]
      },
      {
        "id": "bugatti-veyron",
        "name": "Veyron",
        "brandId": "bugatti",
        "baseVariantId": "bugatti-veyron--bugatti-veyron",
        "variants": [
          {
            "id": "bugatti-veyron--bugatti-veyron",
            "name": "Bugatti Veyron",
            "year": null,
            "url": "/models/bugatti/bugatti_veyron.glb"
          }
        ]
      }
    ]
  },
  {
    "id": "dodge",
    "name": "Dodge",
    "models": [
      {
        "id": "dodge-challenger-rt",
        "name": "Challenger RT",
        "brandId": "dodge",
        "baseVariantId": "dodge-challenger-rt--challenger-rt",
        "variants": [
          {
            "id": "dodge-challenger-rt--challenger-rt",
            "name": "Challenger RT",
            "year": null,
            "url": "/models/dodge/challenger-rt.glb"
          }
        ]
      }
    ]
  },
  {
    "id": "ferrari",
    "name": "Ferrari",
    "models": [
      {
        "id": "ferrari-12cilindri",
        "name": "12Cilindri",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-12cilindri--2025-ferrari-12cilindri",
        "variants": [
          {
            "id": "ferrari-12cilindri--2025-ferrari-12cilindri",
            "name": "2025 Ferrari 12cilindri",
            "year": 2025,
            "url": "/models/ferrari/12Cilindri/2025_ferrari_12cilindri.glb"
          },
          {
            "id": "ferrari-12cilindri--2025-ferrari-12cilindri-spider",
            "name": "2025 Ferrari 12cilindri Spider",
            "year": 2025,
            "url": "/models/ferrari/12Cilindri/2025_ferrari_12cilindri_spider.glb"
          }
        ]
      },
      {
        "id": "ferrari-250-gto",
        "name": "250 GTO",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-250-gto--1962-ferrari-250-gto",
        "variants": [
          {
            "id": "ferrari-250-gto--1962-ferrari-250-gto",
            "name": "1962 Ferrari 250 GTO",
            "year": 1962,
            "url": "/models/ferrari/250_GTO/1962_ferrari_250_gto.glb"
          }
        ]
      },
      {
        "id": "ferrari-296",
        "name": "296",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-296--2022-ferrari-296-gtb",
        "variants": [
          {
            "id": "ferrari-296--2022-ferrari-296-gtb",
            "name": "2022 Ferrari 296 GTB",
            "year": 2022,
            "url": "/models/ferrari/296/2022_ferrari_296_gtb.glb"
          },
          {
            "id": "ferrari-296--2023-ferrari-296-gts",
            "name": "2023 Ferrari 296 GTS",
            "year": 2023,
            "url": "/models/ferrari/296/2023_ferrari_296_gts.glb"
          }
        ]
      },
      {
        "id": "ferrari-348",
        "name": "348",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-348--1989-ferrari-348-tb",
        "variants": [
          {
            "id": "ferrari-348--1989-ferrari-348-tb",
            "name": "1989 Ferrari 348 TB",
            "year": 1989,
            "url": "/models/ferrari/348/1989_ferrari_348_tb.glb"
          }
        ]
      },
      {
        "id": "ferrari-360-modena",
        "name": "360 Modena",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-360-modena--1999-ferrari-360-modena",
        "variants": [
          {
            "id": "ferrari-360-modena--1999-ferrari-360-modena",
            "name": "1999 Ferrari 360 Modena",
            "year": 1999,
            "url": "/models/ferrari/360_Modena/1999_ferrari_360_modena.glb"
          }
        ]
      },
      {
        "id": "ferrari-458",
        "name": "458",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-458--2011-ferrari-458-italia",
        "variants": [
          {
            "id": "ferrari-458--2011-ferrari-458-italia",
            "name": "2011 Ferrari 458 Italia",
            "year": 2011,
            "url": "/models/ferrari/458/2011_ferrari_458_italia.glb"
          },
          {
            "id": "ferrari-458--2013-ferrari-458-spider",
            "name": "2013 Ferrari 458 Spider",
            "year": 2013,
            "url": "/models/ferrari/458/2013_ferrari_458_spider.glb"
          }
        ]
      },
      {
        "id": "ferrari-488",
        "name": "488",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-488--2016-ferrari-488-gtb",
        "variants": [
          {
            "id": "ferrari-488--2016-ferrari-488-gtb",
            "name": "2016 Ferrari 488 GTB",
            "year": 2016,
            "url": "/models/ferrari/488/2016_ferrari_488_gtb.glb"
          },
          {
            "id": "ferrari-488--2018-ferrari-488-gt3",
            "name": "2018 Ferrari 488 GT3",
            "year": 2018,
            "url": "/models/ferrari/488/2018_ferrari_488_gt3.glb"
          },
          {
            "id": "ferrari-488--2019-ferrari-488-pista",
            "name": "2019 Ferrari 488 Pista",
            "year": 2019,
            "url": "/models/ferrari/488/2019_ferrari_488_pista.glb"
          },
          {
            "id": "ferrari-488--2019-ferrari-488-pista-spider",
            "name": "2019 Ferrari 488 Pista Spider",
            "year": 2019,
            "url": "/models/ferrari/488/2019_ferrari_488_pista_spider.glb"
          },
          {
            "id": "ferrari-488--2021-ferrari-488-challenge-evo",
            "name": "2021 Ferrari 488 Challenge EVO",
            "year": 2021,
            "url": "/models/ferrari/488/2021_ferrari_488_challenge_evo.glb"
          },
          {
            "id": "ferrari-488--2021-ferrari-488-gt-modificata",
            "name": "2021 Ferrari 488 GT Modificata",
            "year": 2021,
            "url": "/models/ferrari/488/2021_ferrari_488_gt_modificata.glb"
          }
        ]
      },
      {
        "id": "ferrari-512-tr",
        "name": "512 TR",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-512-tr--1991-ferrari-512-tr",
        "variants": [
          {
            "id": "ferrari-512-tr--1991-ferrari-512-tr",
            "name": "1991 Ferrari 512 TR",
            "year": 1991,
            "url": "/models/ferrari/512_TR/1991_ferrari_512_tr.glb"
          }
        ]
      },
      {
        "id": "ferrari-599",
        "name": "599",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-599--2010-ferrari-599-gto",
        "variants": [
          {
            "id": "ferrari-599--2010-ferrari-599-gto",
            "name": "2010 Ferrari 599 GTO",
            "year": 2010,
            "url": "/models/ferrari/599/2010_ferrari_599_gto.glb"
          }
        ]
      },
      {
        "id": "ferrari-599xx",
        "name": "599XX",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-599xx--2011-ferrari-599xx-evolution",
        "variants": [
          {
            "id": "ferrari-599xx--2011-ferrari-599xx-evolution",
            "name": "2011 Ferrari 599xx Evolution",
            "year": 2011,
            "url": "/models/ferrari/599XX/2011_ferrari_599xx_evolution.glb"
          }
        ]
      },
      {
        "id": "ferrari-612-scaglietti",
        "name": "612 Scaglietti",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-612-scaglietti--2004-ferrari-612-scaglietti",
        "variants": [
          {
            "id": "ferrari-612-scaglietti--2004-ferrari-612-scaglietti",
            "name": "2004 Ferrari 612 Scaglietti",
            "year": 2004,
            "url": "/models/ferrari/612_Scaglietti/2004_ferrari_612_scaglietti.glb"
          }
        ]
      },
      {
        "id": "ferrari-812",
        "name": "812",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-812--2018-ferrari-812-superfast",
        "variants": [
          {
            "id": "ferrari-812--2018-ferrari-812-superfast",
            "name": "2018 Ferrari 812 Superfast",
            "year": 2018,
            "url": "/models/ferrari/812/2018_ferrari_812_superfast.glb"
          },
          {
            "id": "ferrari-812--2020-ferrari-812-gts",
            "name": "2020 Ferrari 812 GTS",
            "year": 2020,
            "url": "/models/ferrari/812/2020_ferrari_812_gts.glb"
          },
          {
            "id": "ferrari-812--2023-ferrari-812-competizione",
            "name": "2023 Ferrari 812 Competizione",
            "year": 2023,
            "url": "/models/ferrari/812/2023_ferrari_812_competizione.glb"
          }
        ]
      },
      {
        "id": "ferrari-california",
        "name": "California",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-california--2008-ferrari-california",
        "variants": [
          {
            "id": "ferrari-california--2008-ferrari-california",
            "name": "2008 Ferrari California",
            "year": 2008,
            "url": "/models/ferrari/California/2008_ferrari_california.glb"
          },
          {
            "id": "ferrari-california--2012-ferrari-california",
            "name": "2012 Ferrari California",
            "year": 2012,
            "url": "/models/ferrari/California/2012_ferrari_california.glb"
          }
        ]
      },
      {
        "id": "ferrari-daytona-sp3",
        "name": "Daytona SP3",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-daytona-sp3--2022-ferrari-daytona-sp3",
        "variants": [
          {
            "id": "ferrari-daytona-sp3--2022-ferrari-daytona-sp3",
            "name": "2022 Ferrari Daytona SP3",
            "year": 2022,
            "url": "/models/ferrari/Daytona_SP3/2022_ferrari_daytona_sp3.glb"
          }
        ]
      },
      {
        "id": "ferrari-enzo",
        "name": "Enzo",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-enzo--2002-ferrari-enzo",
        "variants": [
          {
            "id": "ferrari-enzo--2002-ferrari-enzo",
            "name": "2002 Ferrari Enzo",
            "year": 2002,
            "url": "/models/ferrari/Enzo/2002_ferrari_enzo.glb"
          }
        ]
      },
      {
        "id": "ferrari-f8",
        "name": "F8",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-f8--2020-ferrari-f8-tributo",
        "variants": [
          {
            "id": "ferrari-f8--2020-ferrari-f8-spider",
            "name": "2020 Ferrari F8 Spider",
            "year": 2020,
            "url": "/models/ferrari/F8/2020_ferrari_f8_spider.glb"
          },
          {
            "id": "ferrari-f8--2020-ferrari-f8-tributo",
            "name": "2020 Ferrari F8 Tributo",
            "year": 2020,
            "url": "/models/ferrari/F8/2020_ferrari_f8_tributo.glb"
          }
        ]
      },
      {
        "id": "ferrari-f12",
        "name": "F12",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-f12--2013-ferrari-f12-berlinetta",
        "variants": [
          {
            "id": "ferrari-f12--2013-ferrari-f12-berlinetta",
            "name": "2013 Ferrari F12 Berlinetta",
            "year": 2013,
            "url": "/models/ferrari/F12/2013_ferrari_f12_berlinetta.glb"
          },
          {
            "id": "ferrari-f12--2016-ferrari-f12tdf",
            "name": "2016 Ferrari F12TDF",
            "year": 2016,
            "url": "/models/ferrari/F12/2016_ferrari_f12tdf.glb"
          },
          {
            "id": "ferrari-f12--2017-ferrari-f12-70th-anniversary",
            "name": "2017 Ferrari F12 70th Anniversary",
            "year": 2017,
            "url": "/models/ferrari/F12/2017_ferrari_f12_70th_anniversary.glb"
          }
        ]
      },
      {
        "id": "ferrari-f40",
        "name": "F40",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-f40--1987-ferrari-f40",
        "variants": [
          {
            "id": "ferrari-f40--1987-donnas-ferrari-f40-from-csr2",
            "name": "1987 Donnas Ferrari F40 From CSR2",
            "year": 1987,
            "url": "/models/ferrari/F40/1987_donnas_ferrari_f40_from_csr2.glb"
          },
          {
            "id": "ferrari-f40--1987-ferrari-f40",
            "name": "1987 Ferrari F40",
            "year": 1987,
            "url": "/models/ferrari/F40/1987_ferrari_f40.glb"
          },
          {
            "id": "ferrari-f40--1989-ferrari-f40-lm",
            "name": "1989 Ferrari F40 LM",
            "year": 1989,
            "url": "/models/ferrari/F40/1989_ferrari_f40_lm.glb"
          }
        ]
      },
      {
        "id": "ferrari-f50",
        "name": "F50",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-f50--1995-ferrari-f50",
        "variants": [
          {
            "id": "ferrari-f50--1995-ferrari-f50",
            "name": "1995 Ferrari F50",
            "year": 1995,
            "url": "/models/ferrari/F50/1995_ferrari_f50.glb"
          },
          {
            "id": "ferrari-f50--1995-ferrari-f50-spider",
            "name": "1995 Ferrari F50 Spider",
            "year": 1995,
            "url": "/models/ferrari/F50/1995_ferrari_f50_spider.glb"
          },
          {
            "id": "ferrari-f50--1996-ferrari-f50-gt",
            "name": "1996 Ferrari F50 GT",
            "year": 1996,
            "url": "/models/ferrari/F50/1996_ferrari_f50_gt.glb"
          }
        ]
      },
      {
        "id": "ferrari-f430",
        "name": "F430",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-f430--2005-ferrari-f430",
        "variants": [
          {
            "id": "ferrari-f430--2005-ferrari-f430",
            "name": "2005 Ferrari F430",
            "year": 2005,
            "url": "/models/ferrari/F430/2005_ferrari_f430.glb"
          },
          {
            "id": "ferrari-f430--2008-ferrari-430-scuderia",
            "name": "2008 Ferrari 430 Scuderia",
            "year": 2008,
            "url": "/models/ferrari/F430/2008_ferrari_430_scuderia.glb"
          }
        ]
      },
      {
        "id": "ferrari-ff",
        "name": "FF",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-ff--2012-ferrari-ff",
        "variants": [
          {
            "id": "ferrari-ff--2012-ferrari-ff",
            "name": "2012 Ferrari FF",
            "year": 2012,
            "url": "/models/ferrari/FF/2012_ferrari_ff.glb"
          },
          {
            "id": "ferrari-ff--2012-ferrari-ff-patrol",
            "name": "2012 Ferrari FF Patrol",
            "year": 2012,
            "url": "/models/ferrari/FF/2012_ferrari_ff_-_patrol.glb"
          }
        ]
      },
      {
        "id": "ferrari-fxx",
        "name": "FXX",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-fxx--2008-ferrari-fxx-evolution",
        "variants": [
          {
            "id": "ferrari-fxx--2008-ferrari-fxx-evolution",
            "name": "2008 Ferrari FXX Evolution",
            "year": 2008,
            "url": "/models/ferrari/FXX/2008_ferrari_fxx_evolution.glb"
          }
        ]
      },
      {
        "id": "ferrari-fxx-k",
        "name": "FXX-K",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-fxx-k--2015-ferrari-fxx-k",
        "variants": [
          {
            "id": "ferrari-fxx-k--2015-ferrari-fxx-k",
            "name": "2015 Ferrari FXX K",
            "year": 2015,
            "url": "/models/ferrari/FXX-K/2015_ferrari_fxx_k.glb"
          },
          {
            "id": "ferrari-fxx-k--2018-ferrari-fxx-k-evo",
            "name": "2018 Ferrari FXX K EVO",
            "year": 2018,
            "url": "/models/ferrari/FXX-K/2018_ferrari_fxx-k_evo.glb"
          }
        ]
      },
      {
        "id": "ferrari-gtc4-lusso",
        "name": "GTC4 Lusso",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-gtc4-lusso--2017-ferrari-gtc4-lusso",
        "variants": [
          {
            "id": "ferrari-gtc4-lusso--2017-ferrari-gtc4-lusso",
            "name": "2017 Ferrari GTC4 Lusso",
            "year": 2017,
            "url": "/models/ferrari/GTC4_Lusso/2017_ferrari_gtc4_lusso.glb"
          },
          {
            "id": "ferrari-gtc4-lusso--2018-ferrari-gtc4-lusso-70th-anniversary",
            "name": "2018 Ferrari GTC4 Lusso 70th Anniversary",
            "year": 2018,
            "url": "/models/ferrari/GTC4_Lusso/2018_ferrari_gtc4_lusso_70th_anniversary.glb"
          }
        ]
      },
      {
        "id": "ferrari-j50",
        "name": "J50",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-j50--2017-ferrari-j50",
        "variants": [
          {
            "id": "ferrari-j50--2017-ferrari-j50",
            "name": "2017 Ferrari J50",
            "year": 2017,
            "url": "/models/ferrari/J50/2017_ferrari_j50.glb"
          }
        ]
      },
      {
        "id": "ferrari-laferrari",
        "name": "LaFerrari",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-laferrari--2014-ferrari-laferrari",
        "variants": [
          {
            "id": "ferrari-laferrari--2014-ferrari-laferrari",
            "name": "2014 Ferrari Laferrari",
            "year": 2014,
            "url": "/models/ferrari/LaFerrari/2014_ferrari_laferrari.glb"
          },
          {
            "id": "ferrari-laferrari--2017-ferrari-laferrari-aperta",
            "name": "2017 Ferrari Laferrari Aperta",
            "year": 2017,
            "url": "/models/ferrari/LaFerrari/2017_ferrari_laferrari_aperta.glb"
          }
        ]
      },
      {
        "id": "ferrari-monza",
        "name": "Monza",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-monza--2019-ferrari-monza-sp1",
        "variants": [
          {
            "id": "ferrari-monza--2019-ferrari-monza-sp1",
            "name": "2019 Ferrari Monza SP1",
            "year": 2019,
            "url": "/models/ferrari/Monza/2019_ferrari_monza_sp1.glb"
          },
          {
            "id": "ferrari-monza--2019-ferrari-monza-sp2",
            "name": "2019 Ferrari Monza SP2",
            "year": 2019,
            "url": "/models/ferrari/Monza/2019_ferrari_monza_sp2.glb"
          }
        ]
      },
      {
        "id": "ferrari-p80c",
        "name": "P80C",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-p80c--2019-ferrari-p80c",
        "variants": [
          {
            "id": "ferrari-p80c--2019-ferrari-p80c",
            "name": "2019 Ferrari P80C",
            "year": 2019,
            "url": "/models/ferrari/P80C/2019_ferrari_p80c.glb"
          }
        ]
      },
      {
        "id": "ferrari-portofino",
        "name": "Portofino",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-portofino--2018-ferrari-portofino",
        "variants": [
          {
            "id": "ferrari-portofino--2018-ferrari-portofino",
            "name": "2018 Ferrari Portofino",
            "year": 2018,
            "url": "/models/ferrari/Portofino/2018_ferrari_portofino.glb"
          }
        ]
      },
      {
        "id": "ferrari-purosangue",
        "name": "Purosangue",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-purosangue--2023-ferrari-purosangue",
        "variants": [
          {
            "id": "ferrari-purosangue--2023-ferrari-purosangue",
            "name": "2023 Ferrari Purosangue",
            "year": 2023,
            "url": "/models/ferrari/Purosangue/2023_ferrari_purosangue.glb"
          }
        ]
      },
      {
        "id": "ferrari-roma",
        "name": "Roma",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-roma--2020-ferrari-roma",
        "variants": [
          {
            "id": "ferrari-roma--2020-ferrari-roma",
            "name": "2020 Ferrari Roma",
            "year": 2020,
            "url": "/models/ferrari/Roma/2020_ferrari_roma.glb"
          }
        ]
      },
      {
        "id": "ferrari-sf90",
        "name": "SF90",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-sf90--2020-ferrari-sf90-stradale",
        "variants": [
          {
            "id": "ferrari-sf90--2020-ferrari-sf90-stradale",
            "name": "2020 Ferrari SF90 Stradale",
            "year": 2020,
            "url": "/models/ferrari/SF90/2020_ferrari_sf90_stradale.glb"
          },
          {
            "id": "ferrari-sf90--2021-ferrari-sf90-spider",
            "name": "2021 Ferrari SF90 Spider",
            "year": 2021,
            "url": "/models/ferrari/SF90/2021_ferrari_sf90_spider.glb"
          },
          {
            "id": "ferrari-sf90--2023-ferrari-sf90-xx-stradale",
            "name": "2023 Ferrari SF90 XX Stradale",
            "year": 2023,
            "url": "/models/ferrari/SF90/2023_ferrari_sf90_xx_stradale.glb"
          }
        ]
      },
      {
        "id": "ferrari-sp38",
        "name": "SP38",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-sp38--2018-ferrari-sp38-deborah",
        "variants": [
          {
            "id": "ferrari-sp38--2018-ferrari-sp38-deborah",
            "name": "2018 Ferrari SP38 Deborah",
            "year": 2018,
            "url": "/models/ferrari/SP38/2018_ferrari_sp38_deborah.glb"
          }
        ]
      },
      {
        "id": "ferrari-testarossa",
        "name": "Testarossa",
        "brandId": "ferrari",
        "baseVariantId": "ferrari-testarossa--1984-ferrari-testarossa-f110",
        "variants": [
          {
            "id": "ferrari-testarossa--1984-ferrari-testarossa-f110",
            "name": "1984 Ferrari Testarossa F110",
            "year": 1984,
            "url": "/models/ferrari/Testarossa/1984_ferrari_testarossa_f110.glb"
          },
          {
            "id": "ferrari-testarossa--1988-ferrari-testarossa",
            "name": "1988 Ferrari Testarossa",
            "year": 1988,
            "url": "/models/ferrari/Testarossa/1988_ferrari_testarossa.glb"
          },
          {
            "id": "ferrari-testarossa--2026-ferrari-849-testarossa",
            "name": "2026 Ferrari 849 Testarossa",
            "year": 2026,
            "url": "/models/ferrari/Testarossa/2026_ferrari_849_testarossa.glb"
          }
        ]
      }
    ]
  },
  {
    "id": "ford",
    "name": "Ford",
    "models": [
      {
        "id": "ford-gt40",
        "name": "GT40",
        "brandId": "ford",
        "baseVariantId": "ford-gt40--gt40",
        "variants": [
          {
            "id": "ford-gt40--gt40",
            "name": "GT40",
            "year": null,
            "url": "/models/ford/gt40.glb"
          }
        ]
      }
    ]
  },
  {
    "id": "lamborghini",
    "name": "Lamborghini",
    "models": [
      {
        "id": "lamborghini-asterion",
        "name": "Asterion",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-asterion--2014-lamborghini-asterion-lpi910-4-concept",
        "variants": [
          {
            "id": "lamborghini-asterion--2014-lamborghini-asterion-lpi910-4-concept",
            "name": "2014 Lamborghini Asterion LPI910 4 Concept",
            "year": 2014,
            "url": "/models/lamborghini/Asterion/2014_lamborghini_asterion_lpi910-4_concept.glb"
          }
        ]
      },
      {
        "id": "lamborghini-aventador",
        "name": "Aventador",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-aventador--2011-lamborghini-aventador-lbworks-limited",
        "variants": [
          {
            "id": "lamborghini-aventador--2011-lamborghini-aventador-lbworks-limited",
            "name": "2011 Lamborghini Aventador LBWORKS Limited",
            "year": 2011,
            "url": "/models/lamborghini/Aventador/2011_lamborghini_aventador_lbworks_limited.glb"
          },
          {
            "id": "lamborghini-aventador--2011-lamborghini-aventador-lp-700-4-patrol",
            "name": "2011 Lamborghini Aventador LP 700 4 Patrol",
            "year": 2011,
            "url": "/models/lamborghini/Aventador/2011_lamborghini_aventador_lp_700-4_-_patrol.glb"
          },
          {
            "id": "lamborghini-aventador--2011-lamborghini-aventador-type-1-lbworks",
            "name": "2011 Lamborghini Aventador Type 1 LBWORKS",
            "year": 2011,
            "url": "/models/lamborghini/Aventador/2011_lamborghini_aventador_type_1_lbworks.glb"
          },
          {
            "id": "lamborghini-aventador--2012-lamborghini-aventador-j-concept",
            "name": "2012 Lamborghini Aventador J Concept",
            "year": 2012,
            "url": "/models/lamborghini/Aventador/2012_lamborghini_aventador_j_concept.glb"
          },
          {
            "id": "lamborghini-aventador--2012-lamborghini-aventador-lp700-4",
            "name": "2012 Lamborghini Aventador LP700 4",
            "year": 2012,
            "url": "/models/lamborghini/Aventador/2012_lamborghini_aventador_lp700-4.glb"
          },
          {
            "id": "lamborghini-aventador--2013-mansory-carbonado-lamborghini-aventador",
            "name": "2013 Mansory Carbonado Lamborghini Aventador",
            "year": 2013,
            "url": "/models/lamborghini/Aventador/2013_mansory_carbonado_lamborghini_aventador.glb"
          },
          {
            "id": "lamborghini-aventador--2013-vorsteiner-lamborghini-aventador-v",
            "name": "2013 Vorsteiner Lamborghini Aventador V",
            "year": 2013,
            "url": "/models/lamborghini/Aventador/2013_vorsteiner_lamborghini_aventador-v.glb"
          },
          {
            "id": "lamborghini-aventador--2014-lamborghini-aventador-lbworks",
            "name": "2014 Lamborghini Aventador LBWORKS",
            "year": 2014,
            "url": "/models/lamborghini/Aventador/2014_lamborghini_aventador_lbworks.glb"
          },
          {
            "id": "lamborghini-aventador--2016-lamborghini-aventador-lp750-4-sv",
            "name": "2016 Lamborghini Aventador LP750 4 SV",
            "year": 2016,
            "url": "/models/lamborghini/Aventador/2016_lamborghini_aventador_lp750-4_sv.glb"
          },
          {
            "id": "lamborghini-aventador--2016-lamborghini-aventador-lp750-4-sv-roadster",
            "name": "2016 Lamborghini Aventador LP750 4 SV Roadster",
            "year": 2016,
            "url": "/models/lamborghini/Aventador/2016_lamborghini_aventador_lp750-4_sv_roadster.glb"
          },
          {
            "id": "lamborghini-aventador--2017-lamborghini-aventador-s-lp-740-4",
            "name": "2017 Lamborghini Aventador S LP 740 4",
            "year": 2017,
            "url": "/models/lamborghini/Aventador/2017_lamborghini_aventador_s_lp_740-4.glb"
          },
          {
            "id": "lamborghini-aventador--2018-lamborghini-aventador-lp740-4-s-roadster",
            "name": "2018 Lamborghini Aventador LP740 4 S Roadster",
            "year": 2018,
            "url": "/models/lamborghini/Aventador/2018_lamborghini_aventador_lp740-4_s_roadster.glb"
          },
          {
            "id": "lamborghini-aventador--2019-lamborghini-aventador-duke-dynamics-bodykit",
            "name": "2019 Lamborghini Aventador Duke Dynamics Bodykit",
            "year": 2019,
            "url": "/models/lamborghini/Aventador/2019_lamborghini_aventador_duke_dynamics_bodykit.glb"
          },
          {
            "id": "lamborghini-aventador--2019-lamborghini-aventador-svj",
            "name": "2019 Lamborghini Aventador SVJ",
            "year": 2019,
            "url": "/models/lamborghini/Aventador/2019_lamborghini_aventador_svj.glb"
          },
          {
            "id": "lamborghini-aventador--2019-lamborghini-aventador-svj-63",
            "name": "2019 Lamborghini Aventador SVJ 63",
            "year": 2019,
            "url": "/models/lamborghini/Aventador/2019_lamborghini_aventador_svj_63.glb"
          },
          {
            "id": "lamborghini-aventador--2020-lamborghini-aventador-svj-63-roadster",
            "name": "2020 Lamborghini Aventador SVJ 63 Roadster",
            "year": 2020,
            "url": "/models/lamborghini/Aventador/2020_lamborghini_aventador_svj_63_roadster.glb"
          },
          {
            "id": "lamborghini-aventador--2020-lamborghini-aventador-svj-roadster",
            "name": "2020 Lamborghini Aventador SVJ Roadster",
            "year": 2020,
            "url": "/models/lamborghini/Aventador/2020_lamborghini_aventador_svj_roadster.glb"
          },
          {
            "id": "lamborghini-aventador--2022-lamborghini-aventador-gt-evo-lbsilhouette",
            "name": "2022 Lamborghini Aventador GT EVO LBSILHOUETTE",
            "year": 2022,
            "url": "/models/lamborghini/Aventador/2022_lamborghini_aventador_gt_evo_lbsilhouette.glb"
          },
          {
            "id": "lamborghini-aventador--2022-lamborghini-aventador-lp780-4-ultimae",
            "name": "2022 Lamborghini Aventador LP780 4 Ultimae",
            "year": 2022,
            "url": "/models/lamborghini/Aventador/2022_lamborghini_aventador_lp780-4_ultimae.glb"
          },
          {
            "id": "lamborghini-aventador--2023-svr-lamborghini-aventador-auto-veloce",
            "name": "2023 Svr Lamborghini Aventador Auto Veloce",
            "year": 2023,
            "url": "/models/lamborghini/Aventador/2023_svr_lamborghini_aventador_auto_veloce.glb"
          },
          {
            "id": "lamborghini-aventador--lamborghini-aventador-lp720-4-50th-anniversary",
            "name": "Lamborghini Aventador LP720 4 50th Anniversary",
            "year": null,
            "url": "/models/lamborghini/Aventador/lamborghini_aventador_lp720-4_50th_anniversary.glb"
          }
        ]
      },
      {
        "id": "lamborghini-centenario",
        "name": "Centenario",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-centenario--2017-lamborghini-centenario-lp770-4",
        "variants": [
          {
            "id": "lamborghini-centenario--2017-lamborghini-centenario-lp770-4",
            "name": "2017 Lamborghini Centenario LP770 4",
            "year": 2017,
            "url": "/models/lamborghini/Centenario/2017_lamborghini_centenario_lp770-4.glb"
          },
          {
            "id": "lamborghini-centenario--2017-lamborghini-centenario-roadster",
            "name": "2017 Lamborghini Centenario Roadster",
            "year": 2017,
            "url": "/models/lamborghini/Centenario/2017_lamborghini_centenario_roadster.glb"
          }
        ]
      },
      {
        "id": "lamborghini-countach",
        "name": "Countach",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-countach--1978-lamborghini-countach-lp400s",
        "variants": [
          {
            "id": "lamborghini-countach--1978-lamborghini-countach-lp400s",
            "name": "1978 Lamborghini Countach LP400S",
            "year": 1978,
            "url": "/models/lamborghini/Countach/1978_lamborghini_countach_lp400s.glb"
          },
          {
            "id": "lamborghini-countach--1985-lamborghini-countach-5000-qv",
            "name": "1985 Lamborghini Countach 5000 QV",
            "year": 1985,
            "url": "/models/lamborghini/Countach/1985_lamborghini_countach_5000_qv.glb"
          },
          {
            "id": "lamborghini-countach--1988-lamborghini-countach-5000-qv",
            "name": "1988 Lamborghini Countach 5000 QV",
            "year": 1988,
            "url": "/models/lamborghini/Countach/1988_lamborghini_countach_5000_qv.glb"
          },
          {
            "id": "lamborghini-countach--1989-lamborghini-countach-25th-anniversary",
            "name": "1989 Lamborghini Countach 25th Anniversary",
            "year": 1989,
            "url": "/models/lamborghini/Countach/1989_lamborghini_countach_25th_anniversary.glb"
          },
          {
            "id": "lamborghini-countach--2022-lamborghini-countach-lpi-800-4",
            "name": "2022 Lamborghini Countach Lpi 800 4",
            "year": 2022,
            "url": "/models/lamborghini/Countach/2022_lamborghini_countach_lpi_800-4.glb"
          },
          {
            "id": "lamborghini-countach--2024-lamborghini-countach-lp5000-qv-lbworks",
            "name": "2024 Lamborghini Countach LP5000 QV LBWORKS",
            "year": 2024,
            "url": "/models/lamborghini/Countach/2024_lamborghini_countach_lp5000_qv_lbworks.glb"
          }
        ]
      },
      {
        "id": "lamborghini-diablo",
        "name": "Diablo",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-diablo--1995-lamborghini-diablo-sv",
        "variants": [
          {
            "id": "lamborghini-diablo--1995-lamborghini-diablo-sv",
            "name": "1995 Lamborghini Diablo SV",
            "year": 1995,
            "url": "/models/lamborghini/Diablo/1995_lamborghini_diablo_sv.glb"
          }
        ]
      },
      {
        "id": "lamborghini-egoista",
        "name": "Egoista",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-egoista--2013-lamborghini-egoista-concept",
        "variants": [
          {
            "id": "lamborghini-egoista--2013-lamborghini-egoista-concept",
            "name": "2013 Lamborghini Egoista Concept",
            "year": 2013,
            "url": "/models/lamborghini/Egoista/2013_lamborghini_egoista_concept.glb"
          }
        ]
      },
      {
        "id": "lamborghini-estoque",
        "name": "Estoque",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-estoque--2008-lamborghini-estoque-concept",
        "variants": [
          {
            "id": "lamborghini-estoque--2008-lamborghini-estoque-concept",
            "name": "2008 Lamborghini Estoque Concept",
            "year": 2008,
            "url": "/models/lamborghini/Estoque/2008_lamborghini_estoque_concept.glb"
          }
        ]
      },
      {
        "id": "lamborghini-gallardo",
        "name": "Gallardo",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-gallardo--2009-lamborghini-gallardo-lp560-4",
        "variants": [
          {
            "id": "lamborghini-gallardo--2009-lamborghini-gallardo-lp560-4",
            "name": "2009 Lamborghini Gallardo LP560 4",
            "year": 2009,
            "url": "/models/lamborghini/Gallardo/2009_lamborghini_gallardo_lp560-4.glb"
          },
          {
            "id": "lamborghini-gallardo--2009-lamborghini-gallardo-lp560-4-spyder",
            "name": "2009 Lamborghini Gallardo LP560 4 Spyder",
            "year": 2009,
            "url": "/models/lamborghini/Gallardo/2009_lamborghini_gallardo_lp560-4_spyder.glb"
          },
          {
            "id": "lamborghini-gallardo--2010-lamborghini-gallardo-lp550-2",
            "name": "2010 Lamborghini Gallardo LP550 2",
            "year": 2010,
            "url": "/models/lamborghini/Gallardo/2010_lamborghini_gallardo_lp550-2.glb"
          },
          {
            "id": "lamborghini-gallardo--2011-lamborghini-gallardo-lp560-gt3",
            "name": "2011 Lamborghini Gallardo LP560 GT3",
            "year": 2011,
            "url": "/models/lamborghini/Gallardo/2011_lamborghini_gallardo_lp560_gt3.glb"
          },
          {
            "id": "lamborghini-gallardo--2011-lamborghini-gallardo-lp570-4-superleggera",
            "name": "2011 Lamborghini Gallardo LP570 4 Superleggera",
            "year": 2011,
            "url": "/models/lamborghini/Gallardo/2011_lamborghini_gallardo_lp570-4_superleggera.glb"
          },
          {
            "id": "lamborghini-gallardo--2011-west-yokohama-lamborghini-gallardo-lp560-4",
            "name": "2011 West Yokohama Lamborghini Gallardo LP560 4",
            "year": 2011,
            "url": "/models/lamborghini/Gallardo/2011_west_yokohama_lamborghini_gallardo_lp560-4.glb"
          },
          {
            "id": "lamborghini-gallardo--2013-lamborghini-gallardo-lp560-4",
            "name": "2013 Lamborghini Gallardo LP560 4",
            "year": 2013,
            "url": "/models/lamborghini/Gallardo/2013_lamborghini_gallardo_lp560-4.glb"
          },
          {
            "id": "lamborghini-gallardo--2013-lamborghini-gallardo-lp570-4-super-trofeo",
            "name": "2013 Lamborghini Gallardo LP570 4 Super Trofeo",
            "year": 2013,
            "url": "/models/lamborghini/Gallardo/2013_lamborghini_gallardo_lp570-4_super_trofeo.glb"
          },
          {
            "id": "lamborghini-gallardo--2013-lamborghini-gallardo-lp570-4-tecnica",
            "name": "2013 Lamborghini Gallardo LP570 4 Tecnica",
            "year": 2013,
            "url": "/models/lamborghini/Gallardo/2013_lamborghini_gallardo_lp570-4_tecnica.glb"
          },
          {
            "id": "lamborghini-gallardo--gallardo-lp560-4-spyder-nfs-mobile-widebody",
            "name": "Gallardo LP560 4 Spyder NFS Mobile Widebody",
            "year": null,
            "url": "/models/lamborghini/Gallardo/gallardo_lp560-4_spyder_nfs_mobile_widebody.glb"
          }
        ]
      },
      {
        "id": "lamborghini-huracan",
        "name": "Huracan",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-huracan--2015-lamborghini-huracan-coupe-lbworks-body-kit",
        "variants": [
          {
            "id": "lamborghini-huracan--2015-lamborghini-huracan-coupe-lbworks-body-kit",
            "name": "2015 Lamborghini Huracan Coupe LBWORKS Body Kit",
            "year": 2015,
            "url": "/models/lamborghini/Huracan/2015_lamborghini_huracan_coupe_lbworks_body_kit.glb"
          },
          {
            "id": "lamborghini-huracan--2015-lamborghini-huracan-gt3-racecar",
            "name": "2015 Lamborghini Huracan GT3 Racecar",
            "year": 2015,
            "url": "/models/lamborghini/Huracan/2015_lamborghini_huracan_gt3_racecar.glb"
          },
          {
            "id": "lamborghini-huracan--2015-lamborghini-huracan-lp610-4",
            "name": "2015 Lamborghini Huracan LP610 4",
            "year": 2015,
            "url": "/models/lamborghini/Huracan/2015_lamborghini_huracan_lp610-4.glb"
          },
          {
            "id": "lamborghini-huracan--2015-mansory-huracan-torofeo",
            "name": "2015 Mansory Huracan Torofeo",
            "year": 2015,
            "url": "/models/lamborghini/Huracan/2015_mansory_huracan_torofeo.glb"
          },
          {
            "id": "lamborghini-huracan--2015-mansory-huracan-torofeo-full-carbon",
            "name": "2015 Mansory Huracan Torofeo Full Carbon",
            "year": 2015,
            "url": "/models/lamborghini/Huracan/2015_mansory_huracan_torofeo_full_carbon.glb"
          },
          {
            "id": "lamborghini-huracan--2017-lamborghini-huracan-lp580-2",
            "name": "2017 Lamborghini Huracan LP580 2",
            "year": 2017,
            "url": "/models/lamborghini/Huracan/2017_lamborghini_huracan_lp580-2.glb"
          },
          {
            "id": "lamborghini-huracan--2017-lamborghini-huracan-mansory",
            "name": "2017 Lamborghini Huracan Mansory",
            "year": 2017,
            "url": "/models/lamborghini/Huracan/2017_lamborghini_huracan_mansory.glb"
          },
          {
            "id": "lamborghini-huracan--2018-lamborghini-huracan-performante",
            "name": "2018 Lamborghini Huracan Performante",
            "year": 2018,
            "url": "/models/lamborghini/Huracan/2018_lamborghini_huracan_performante.glb"
          },
          {
            "id": "lamborghini-huracan--2018-lamborghini-huracan-super-trofeo-evo",
            "name": "2018 Lamborghini Huracan Super Trofeo EVO",
            "year": 2018,
            "url": "/models/lamborghini/Huracan/2018_lamborghini_huracan_super_trofeo_evo.glb"
          },
          {
            "id": "lamborghini-huracan--2019-lamborghini-huracan-evo-1",
            "name": "2019 Lamborghini Huracan EVO (1)",
            "year": 2019,
            "url": "/models/lamborghini/Huracan/2019_lamborghini_huracan_evo (1).glb"
          },
          {
            "id": "lamborghini-huracan--2019-lamborghini-huracan-evo",
            "name": "2019 Lamborghini Huracan EVO",
            "year": 2019,
            "url": "/models/lamborghini/Huracan/2019_lamborghini_huracan_evo.glb"
          },
          {
            "id": "lamborghini-huracan--2019-lamborghini-huracan-evo-spyder",
            "name": "2019 Lamborghini Huracan EVO Spyder",
            "year": 2019,
            "url": "/models/lamborghini/Huracan/2019_lamborghini_huracan_evo_spyder.glb"
          },
          {
            "id": "lamborghini-huracan--2019-lamborghini-huracan-gt3-evo-racecar",
            "name": "2019 Lamborghini Huracan GT3 EVO Racecar",
            "year": 2019,
            "url": "/models/lamborghini/Huracan/2019_lamborghini_huracan_gt3_evo_racecar.glb"
          },
          {
            "id": "lamborghini-huracan--2019-lamborghini-huracan-gt-lbsilhouette",
            "name": "2019 Lamborghini Huracan GT LBSILHOUETTE",
            "year": 2019,
            "url": "/models/lamborghini/Huracan/2019_lamborghini_huracan_gt_lbsilhouette.glb"
          },
          {
            "id": "lamborghini-huracan--2019-lamborghini-huracan-performante-spyder",
            "name": "2019 Lamborghini Huracan Performante Spyder",
            "year": 2019,
            "url": "/models/lamborghini/Huracan/2019_lamborghini_huracan_performante_spyder.glb"
          },
          {
            "id": "lamborghini-huracan--2021-lamborghini-huracan-evo-rwd-spyder",
            "name": "2021 Lamborghini Huracan EVO RWD Spyder",
            "year": 2021,
            "url": "/models/lamborghini/Huracan/2021_lamborghini_huracan_evo_rwd_spyder.glb"
          },
          {
            "id": "lamborghini-huracan--2021-lamborghini-huracan-sto",
            "name": "2021 Lamborghini Huracan Sto",
            "year": 2021,
            "url": "/models/lamborghini/Huracan/2021_lamborghini_huracan_sto.glb"
          },
          {
            "id": "lamborghini-huracan--2021-vorsteiner-lamborghini-huracan-evo-2wd",
            "name": "2021 Vorsteiner Lamborghini Huracan EVO 2wd",
            "year": 2021,
            "url": "/models/lamborghini/Huracan/2021_vorsteiner_lamborghini_huracan_evo_2wd.glb"
          },
          {
            "id": "lamborghini-huracan--2022-lamborghini-huracan-super-trofeo-evo2-carb",
            "name": "2022 Lamborghini Huracan Super Trofeo EVO2 Carb",
            "year": 2022,
            "url": "/models/lamborghini/Huracan/2022_lamborghini_huracan_super_trofeo_evo2_carb.glb"
          },
          {
            "id": "lamborghini-huracan--2023-lamborghini-huracan-gt3-evo-2",
            "name": "2023 Lamborghini Huracan GT3 EVO 2",
            "year": 2023,
            "url": "/models/lamborghini/Huracan/2023_lamborghini_huracan_gt3_evo_2.glb"
          },
          {
            "id": "lamborghini-huracan--2023-lamborghini-huracan-tecnica",
            "name": "2023 Lamborghini Huracan Tecnica",
            "year": 2023,
            "url": "/models/lamborghini/Huracan/2023_lamborghini_huracan_tecnica.glb"
          },
          {
            "id": "lamborghini-huracan--2024-lamborghini-huracan-sterrato-1",
            "name": "2024 Lamborghini Huracan Sterrato (1)",
            "year": 2024,
            "url": "/models/lamborghini/Huracan/2024_lamborghini_huracan_sterrato (1).glb"
          },
          {
            "id": "lamborghini-huracan--2024-lamborghini-huracan-sterrato",
            "name": "2024 Lamborghini Huracan Sterrato",
            "year": 2024,
            "url": "/models/lamborghini/Huracan/2024_lamborghini_huracan_sterrato.glb"
          }
        ]
      },
      {
        "id": "lamborghini-invencible",
        "name": "Invencible",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-invencible--2023-lamborghini-invencible",
        "variants": [
          {
            "id": "lamborghini-invencible--2023-lamborghini-invencible",
            "name": "2023 Lamborghini Invencible",
            "year": 2023,
            "url": "/models/lamborghini/Invencible/2023_lamborghini_invencible.glb"
          }
        ]
      },
      {
        "id": "lamborghini-lanzador",
        "name": "Lanzador",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-lanzador--2023-lamborghini-lanzador-concept",
        "variants": [
          {
            "id": "lamborghini-lanzador--2023-lamborghini-lanzador-concept",
            "name": "2023 Lamborghini Lanzador Concept",
            "year": 2023,
            "url": "/models/lamborghini/Lanzador/2023_lamborghini_lanzador_concept.glb"
          }
        ]
      },
      {
        "id": "lamborghini-miura",
        "name": "Miura",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-miura--1968-lamborghini-miura-p400",
        "variants": [
          {
            "id": "lamborghini-miura--1968-lamborghini-miura-p400",
            "name": "1968 Lamborghini Miura P400",
            "year": 1968,
            "url": "/models/lamborghini/Miura/1968_lamborghini_miura_p400.glb"
          },
          {
            "id": "lamborghini-miura--2006-lamborghini-miura-concept",
            "name": "2006 Lamborghini Miura Concept",
            "year": 2006,
            "url": "/models/lamborghini/Miura/2006_lamborghini_miura_concept.glb"
          }
        ]
      },
      {
        "id": "lamborghini-murcielago",
        "name": "Murcielago",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-murcielago--2003-fast-furious-lamborghini-murcielago-lp640",
        "variants": [
          {
            "id": "lamborghini-murcielago--2003-fast-furious-lamborghini-murcielago-lp640",
            "name": "2003 Fast Furious Lamborghini Murcielago LP640",
            "year": 2003,
            "url": "/models/lamborghini/Murcielago/2003_fast__furious_lamborghini_murcielago_lp640.glb"
          },
          {
            "id": "lamborghini-murcielago--2006-lamborghini-murcielago-lp640",
            "name": "2006 Lamborghini Murcielago LP640",
            "year": 2006,
            "url": "/models/lamborghini/Murcielago/2006_lamborghini_murcielago_lp640.glb"
          },
          {
            "id": "lamborghini-murcielago--2007-lamborghini-murcielago-lp640",
            "name": "2007 Lamborghini Murcielago LP640",
            "year": 2007,
            "url": "/models/lamborghini/Murcielago/2007_lamborghini_murcielago_lp640.glb"
          },
          {
            "id": "lamborghini-murcielago--2009-lamborghini-murcielago-lbworks-body-kit",
            "name": "2009 Lamborghini Murcielago LBWORKS Body Kit",
            "year": 2009,
            "url": "/models/lamborghini/Murcielago/2009_lamborghini_murcielago_lbworks_body_kit.glb"
          },
          {
            "id": "lamborghini-murcielago--2010-lamborghini-murcielago-lp650-4-roadster",
            "name": "2010 Lamborghini Murcielago LP650 4 Roadster",
            "year": 2010,
            "url": "/models/lamborghini/Murcielago/2010__lamborghini_murcielago_lp650-4_roadster.glb"
          },
          {
            "id": "lamborghini-murcielago--2010-lamborghini-murcielago-lp670-4-superveloce",
            "name": "2010 Lamborghini Murcielago LP670 4 Superveloce",
            "year": 2010,
            "url": "/models/lamborghini/Murcielago/2010_lamborghini_murcielago_lp670-4_superveloce.glb"
          },
          {
            "id": "lamborghini-murcielago--2024-lbsilhouette-works-murcielago-gt-evo",
            "name": "2024 LBSILHOUETTE Works Murcielago GT EVO",
            "year": 2024,
            "url": "/models/lamborghini/Murcielago/2024_lbsilhouette_works_murcielago_gt_evo.glb"
          }
        ]
      },
      {
        "id": "lamborghini-reventon",
        "name": "Reventon",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-reventon--2008-lamborghini-reventon",
        "variants": [
          {
            "id": "lamborghini-reventon--2008-lamborghini-reventon",
            "name": "2008 Lamborghini Reventon",
            "year": 2008,
            "url": "/models/lamborghini/Reventon/2008_lamborghini_reventon.glb"
          },
          {
            "id": "lamborghini-reventon--2010-lamborghini-reventon-roadster",
            "name": "2010 Lamborghini Reventon Roadster",
            "year": 2010,
            "url": "/models/lamborghini/Reventon/2010_lamborghini_reventon_roadster.glb"
          }
        ]
      },
      {
        "id": "lamborghini-sc20",
        "name": "SC20",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-sc20--2020-lamborghini-sc20",
        "variants": [
          {
            "id": "lamborghini-sc20--2020-lamborghini-sc20",
            "name": "2020 Lamborghini SC20",
            "year": 2020,
            "url": "/models/lamborghini/SC20/2020_lamborghini_sc20.glb"
          }
        ]
      },
      {
        "id": "lamborghini-sc63",
        "name": "SC63",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-sc63--2024-lamborghini-sc63-lmdh",
        "variants": [
          {
            "id": "lamborghini-sc63--2024-lamborghini-sc63-lmdh",
            "name": "2024 Lamborghini SC63 LMDH",
            "year": 2024,
            "url": "/models/lamborghini/SC63/2024_lamborghini_sc63_lmdh.glb"
          }
        ]
      },
      {
        "id": "lamborghini-sesto-elemento",
        "name": "Sesto Elemento",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-sesto-elemento--2012-lamborghini-sesto-elemento",
        "variants": [
          {
            "id": "lamborghini-sesto-elemento--2012-lamborghini-sesto-elemento",
            "name": "2012 Lamborghini Sesto Elemento",
            "year": 2012,
            "url": "/models/lamborghini/Sesto_Elemento/2012_lamborghini_sesto_elemento.glb"
          }
        ]
      },
      {
        "id": "lamborghini-sian",
        "name": "Sian",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-sian--2020-lamborghini-sian-fkp-37",
        "variants": [
          {
            "id": "lamborghini-sian--2020-lamborghini-sian-fkp-37",
            "name": "2020 Lamborghini Sian Fkp 37",
            "year": 2020,
            "url": "/models/lamborghini/Sian/2020_lamborghini_sian_fkp_37.glb"
          },
          {
            "id": "lamborghini-sian--2020-lamborghini-sian-fkp-37-ad-personam",
            "name": "2020 Lamborghini Sian Fkp 37 AD Personam",
            "year": 2020,
            "url": "/models/lamborghini/Sian/2020_lamborghini_sian_fkp_37_ad_personam.glb"
          },
          {
            "id": "lamborghini-sian--2021-lamborghini-sian-roadster",
            "name": "2021 Lamborghini Sian Roadster",
            "year": 2021,
            "url": "/models/lamborghini/Sian/2021_lamborghini_sian_roadster.glb"
          }
        ]
      },
      {
        "id": "lamborghini-urus",
        "name": "Urus",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-urus--2019-lamborghini-urus",
        "variants": [
          {
            "id": "lamborghini-urus--2019-lamborghini-urus",
            "name": "2019 Lamborghini Urus",
            "year": 2019,
            "url": "/models/lamborghini/Urus/2019_lamborghini_urus.glb"
          },
          {
            "id": "lamborghini-urus--2019-mansory-venatus-lamborghini-urus",
            "name": "2019 Mansory Venatus Lamborghini Urus",
            "year": 2019,
            "url": "/models/lamborghini/Urus/2019_mansory_venatus_lamborghini_urus.glb"
          },
          {
            "id": "lamborghini-urus--2023-lamborghini-urus-performante",
            "name": "2023 Lamborghini Urus Performante",
            "year": 2023,
            "url": "/models/lamborghini/Urus/2023_lamborghini_urus_performante.glb"
          },
          {
            "id": "lamborghini-urus--2025-lamborghini-urus-se",
            "name": "2025 Lamborghini Urus SE",
            "year": 2025,
            "url": "/models/lamborghini/Urus/2025_lamborghini_urus_se.glb"
          }
        ]
      },
      {
        "id": "lamborghini-veneno",
        "name": "Veneno",
        "brandId": "lamborghini",
        "baseVariantId": "lamborghini-veneno--2013-lamborghini-veneno",
        "variants": [
          {
            "id": "lamborghini-veneno--2013-lamborghini-veneno",
            "name": "2013 Lamborghini Veneno",
            "year": 2013,
            "url": "/models/lamborghini/Veneno/2013_lamborghini_veneno.glb"
          },
          {
            "id": "lamborghini-veneno--2014-lamborghini-veneno-roadster",
            "name": "2014 Lamborghini Veneno Roadster",
            "year": 2014,
            "url": "/models/lamborghini/Veneno/2014_lamborghini_veneno_roadster.glb"
          }
        ]
      }
    ]
  },
  {
    "id": "porsche",
    "name": "Porsche",
    "models": [
      {
        "id": "porsche-718-boxster-spyder",
        "name": "718 Boxster Spyder",
        "brandId": "porsche",
        "baseVariantId": "porsche-718-boxster-spyder--2015-porsche-boxster-gts-718",
        "variants": [
          {
            "id": "porsche-718-boxster-spyder--2010-porsche-boxster-spyder",
            "name": "2010 Porsche Boxster Spyder",
            "year": 2010,
            "url": "/models/porsche/718_Boxster_Spyder/2010_porsche_boxster_spyder.glb"
          },
          {
            "id": "porsche-718-boxster-spyder--2015-porsche-boxster-gts-718",
            "name": "2015 Porsche Boxster GTS 718",
            "year": 2015,
            "url": "/models/porsche/718_Boxster_Spyder/2015_porsche_boxster_gts_718.glb"
          },
          {
            "id": "porsche-718-boxster-spyder--2017-porsche-718-boxster-s",
            "name": "2017 Porsche 718 Boxster S",
            "year": 2017,
            "url": "/models/porsche/718_Boxster_Spyder/2017_porsche_718_boxster_s.glb"
          },
          {
            "id": "porsche-718-boxster-spyder--2019-porsche-718-boxster-t",
            "name": "2019 Porsche 718 Boxster T",
            "year": 2019,
            "url": "/models/porsche/718_Boxster_Spyder/2019_porsche_718_boxster_t.glb"
          },
          {
            "id": "porsche-718-boxster-spyder--2020-porsche-718-spyder",
            "name": "2020 Porsche 718 Spyder",
            "year": 2020,
            "url": "/models/porsche/718_Boxster_Spyder/2020_porsche_718_spyder.glb"
          },
          {
            "id": "porsche-718-boxster-spyder--2024-porsche-718-spyder-rs",
            "name": "2024 Porsche 718 Spyder RS",
            "year": 2024,
            "url": "/models/porsche/718_Boxster_Spyder/2024_porsche_718_spyder_rs.glb"
          }
        ]
      },
      {
        "id": "porsche-718-cayman",
        "name": "718 Cayman",
        "brandId": "porsche",
        "baseVariantId": "porsche-718-cayman--2014-porsche-cayman-s-981",
        "variants": [
          {
            "id": "porsche-718-cayman--2014-porsche-cayman-s-981",
            "name": "2014 Porsche Cayman S 981",
            "year": 2014,
            "url": "/models/porsche/718_Cayman/2014_porsche_cayman_s_981.glb"
          },
          {
            "id": "porsche-718-cayman--2017-porsche-718-cayman-982",
            "name": "2017 Porsche 718 Cayman 982",
            "year": 2017,
            "url": "/models/porsche/718_Cayman/2017_porsche_718_cayman_982.glb"
          },
          {
            "id": "porsche-718-cayman--2018-porsche-718-cayman-gts",
            "name": "2018 Porsche 718 Cayman GTS",
            "year": 2018,
            "url": "/models/porsche/718_Cayman/2018_porsche_718_cayman_gts.glb"
          },
          {
            "id": "porsche-718-cayman--2020-porsche-718-cayman-gt4",
            "name": "2020 Porsche 718 Cayman GT4",
            "year": 2020,
            "url": "/models/porsche/718_Cayman/2020_porsche_718_cayman_gt4.glb"
          },
          {
            "id": "porsche-718-cayman--2022-porsche-718-cayman-gt4-rs",
            "name": "2022 Porsche 718 Cayman GT4 RS",
            "year": 2022,
            "url": "/models/porsche/718_Cayman/2022_porsche_718_cayman_gt4_rs.glb"
          }
        ]
      },
      {
        "id": "porsche-911",
        "name": "911",
        "brandId": "porsche",
        "baseVariantId": "porsche-911--1982-porsche-930-911-turbo-3-3",
        "variants": [
          {
            "id": "porsche-911--1982-porsche-930-911-turbo-3-3",
            "name": "1982 Porsche 930 911 Turbo 3.3",
            "year": 1982,
            "url": "/models/porsche/911/1982_porsche_930_911_turbo_3.3.glb"
          },
          {
            "id": "porsche-911--1989-porsche-911-964-carrera-4",
            "name": "1989 Porsche 911 964 Carrera 4",
            "year": 1989,
            "url": "/models/porsche/911/1989_porsche_911_964_carrera_4.glb"
          },
          {
            "id": "porsche-911--1991-rwb-porsche-911-964",
            "name": "1991 RWB Porsche 911 964",
            "year": 1991,
            "url": "/models/porsche/911/1991_rwb_porsche_911_964.glb"
          },
          {
            "id": "porsche-911--1992-porsche-911-964-turbo-s-3-6",
            "name": "1992 Porsche 911 964 Turbo S 3.6",
            "year": 1992,
            "url": "/models/porsche/911/1992_porsche_911_964_turbo_s_3.6.glb"
          },
          {
            "id": "porsche-911--1995-porsche-911-carrera-rs-993",
            "name": "1995 Porsche 911 Carrera RS 993",
            "year": 1995,
            "url": "/models/porsche/911/1995_porsche_911_carrera_rs_993.glb"
          },
          {
            "id": "porsche-911--1995-porsche-911-gt2-993",
            "name": "1995 Porsche 911 GT2 993",
            "year": 1995,
            "url": "/models/porsche/911/1995_porsche_911_gt2_993.glb"
          },
          {
            "id": "porsche-911--1997-porsche-911-carrera-s-993",
            "name": "1997 Porsche 911 Carrera S 993",
            "year": 1997,
            "url": "/models/porsche/911/1997_porsche_911_carrera_s_993.glb"
          },
          {
            "id": "porsche-911--1998-porsche-911-gt1",
            "name": "1998 Porsche 911 GT1",
            "year": 1998,
            "url": "/models/porsche/911/1998_porsche_911_gt1.glb"
          },
          {
            "id": "porsche-911--1998-porsche-911-gt1-straenversion",
            "name": "1998 Porsche 911 GT1 Straenversion",
            "year": 1998,
            "url": "/models/porsche/911/1998_porsche_911_gt1_straenversion.glb"
          },
          {
            "id": "porsche-911--2002-porsche-911-turbo-996",
            "name": "2002 Porsche 911 Turbo 996",
            "year": 2002,
            "url": "/models/porsche/911/2002_porsche_911_turbo_996.glb"
          },
          {
            "id": "porsche-911--2011-porsche-911-speedster-997-2",
            "name": "2011 Porsche 911 Speedster 997 2",
            "year": 2011,
            "url": "/models/porsche/911/2011_porsche_911_speedster_997-2.glb"
          },
          {
            "id": "porsche-911--2014-porsche-911-gt3-991",
            "name": "2014 Porsche 911 GT3 991",
            "year": 2014,
            "url": "/models/porsche/911/2014_porsche_911_gt3_991.glb"
          },
          {
            "id": "porsche-911--2016-porsche-911-turbo-s-991-2",
            "name": "2016 Porsche 911 Turbo S 991.2",
            "year": 2016,
            "url": "/models/porsche/911/2016_porsche_911_turbo_s_991.2.glb"
          },
          {
            "id": "porsche-911--2017-porsche-911-991-gt3-rs",
            "name": "2017 Porsche 911 991 GT3 RS",
            "year": 2017,
            "url": "/models/porsche/911/2017_porsche_911_991_gt3_rs.glb"
          },
          {
            "id": "porsche-911--2017-porsche-911-turbo-s-exclusive-series-991-2",
            "name": "2017 Porsche 911 Turbo S Exclusive Series 991.2",
            "year": 2017,
            "url": "/models/porsche/911/2017_porsche_911_turbo_s_exclusive_series_991.2.glb"
          },
          {
            "id": "porsche-911--2017-porsche-gt-rsr-991-duke-dynamics-widebody",
            "name": "2017 Porsche GT Rsr 991 Duke Dynamics Widebody",
            "year": 2017,
            "url": "/models/porsche/911/2017_porsche_gt-rsr_991_duke_dynamics_widebody.glb"
          },
          {
            "id": "porsche-911--2018-porsche-911-carrera-gts",
            "name": "2018 Porsche 911 Carrera GTS",
            "year": 2018,
            "url": "/models/porsche/911/2018_porsche_911_carrera_gts.glb"
          },
          {
            "id": "porsche-911--2018-porsche-911-gt2-rs-clubsport",
            "name": "2018 Porsche 911 GT2 RS Clubsport",
            "year": 2018,
            "url": "/models/porsche/911/2018_porsche_911_gt2_rs_clubsport.glb"
          },
          {
            "id": "porsche-911--2018-porsche-911-gt2-rs-weissach-package",
            "name": "2018 Porsche 911 GT2 RS Weissach Package",
            "year": 2018,
            "url": "/models/porsche/911/2018_porsche_911_gt2_rs_weissach_package.glb"
          },
          {
            "id": "porsche-911--2019-porsche-911-991-2-gt3-rs",
            "name": "2019 Porsche 911 991.2 GT3 RS",
            "year": 2019,
            "url": "/models/porsche/911/2019_porsche_911_991.2_gt3_rs.glb"
          },
          {
            "id": "porsche-911--2019-porsche-911-991-2-gt3-rs-weissach-package",
            "name": "2019 Porsche 911 991.2 GT3 RS Weissach Package",
            "year": 2019,
            "url": "/models/porsche/911/2019_porsche_911_991.2_gt3_rs_weissach_package.glb"
          },
          {
            "id": "porsche-911--2019-porsche-911-carrera-4s-992",
            "name": "2019 Porsche 911 Carrera 4s 992",
            "year": 2019,
            "url": "/models/porsche/911/2019_porsche_911_carrera_4s_992.glb"
          },
          {
            "id": "porsche-911--2019-porsche-911-carrera-4s-cabriolet-992",
            "name": "2019 Porsche 911 Carrera 4s Cabriolet 992",
            "year": 2019,
            "url": "/models/porsche/911/2019_porsche_911_carrera_4s_cabriolet_992.glb"
          },
          {
            "id": "porsche-911--2019-porsche-911-gt2-rs-clubsport-23-salzburg",
            "name": "2019 Porsche 911 GT2 RS Clubsport 23 Salzburg",
            "year": 2019,
            "url": "/models/porsche/911/2019_porsche_911_gt2_rs_clubsport_23_salzburg.glb"
          },
          {
            "id": "porsche-911--2019-porsche-911-speedster-991-2",
            "name": "2019 Porsche 911 Speedster 991.2",
            "year": 2019,
            "url": "/models/porsche/911/2019_porsche_911_speedster_991.2.glb"
          },
          {
            "id": "porsche-911--2019-porsche-911-speedster-heritage-edition",
            "name": "2019 Porsche 911 Speedster Heritage Edition",
            "year": 2019,
            "url": "/models/porsche/911/2019_porsche_911_speedster_heritage_edition.glb"
          },
          {
            "id": "porsche-911--2019-porsche-911-targa-4s-991-2",
            "name": "2019 Porsche 911 Targa 4s 991.2",
            "year": 2019,
            "url": "/models/porsche/911/2019_porsche_911_targa_4s_991.2.glb"
          },
          {
            "id": "porsche-911--2021-porsche-911-targa-4s-992",
            "name": "2021 Porsche 911 Targa 4s 992",
            "year": 2021,
            "url": "/models/porsche/911/2021_porsche_911_targa_4s_992.glb"
          },
          {
            "id": "porsche-911--2021-porsche-911-targa-4s-heritage-design-992",
            "name": "2021 Porsche 911 Targa 4s Heritage Design 992",
            "year": 2021,
            "url": "/models/porsche/911/2021_porsche_911_targa_4s_heritage_design_992.glb"
          },
          {
            "id": "porsche-911--2021-porsche-911-turbo-s-992",
            "name": "2021 Porsche 911 Turbo S 992",
            "year": 2021,
            "url": "/models/porsche/911/2021_porsche_911_turbo_s_992.glb"
          },
          {
            "id": "porsche-911--2022-porsche-911-gt3-992",
            "name": "2022 Porsche 911 GT3 992",
            "year": 2022,
            "url": "/models/porsche/911/2022_porsche_911_gt3_992.glb"
          },
          {
            "id": "porsche-911--2022-porsche-911-gt3-touring-992",
            "name": "2022 Porsche 911 GT3 Touring 992",
            "year": 2022,
            "url": "/models/porsche/911/2022_porsche_911_gt3_touring_992.glb"
          },
          {
            "id": "porsche-911--2023-porsche-911-gt3-rs-2-7-carrera-tribute-992",
            "name": "2023 Porsche 911 GT3 RS 2.7 Carrera Tribute 992",
            "year": 2023,
            "url": "/models/porsche/911/2023_porsche_911_gt3_rs_2.7_carrera_tribute_992.glb"
          },
          {
            "id": "porsche-911--2024-porsche-911-st",
            "name": "2024 Porsche 911 ST",
            "year": 2024,
            "url": "/models/porsche/911/2024_porsche_911_st.glb"
          },
          {
            "id": "porsche-911--2025-porsche-911-gt3-992-2",
            "name": "2025 Porsche 911 GT3 992 2",
            "year": 2025,
            "url": "/models/porsche/911/2025_porsche_911_gt3_992-2.glb"
          },
          {
            "id": "porsche-911--2025-porsche-911-targa-4-gts",
            "name": "2025 Porsche 911 Targa 4 GTS",
            "year": 2025,
            "url": "/models/porsche/911/2025_porsche_911_targa_4_gts.glb"
          },
          {
            "id": "porsche-911--free-1975-porsche-911-930-turbo",
            "name": "Free 1975 Porsche 911 930 Turbo",
            "year": null,
            "url": "/models/porsche/911/free_1975_porsche_911_930_turbo.glb"
          },
          {
            "id": "porsche-911--magnus-walkers-1971-porsche-911-277",
            "name": "Magnus Walkers 1971 Porsche 911 277",
            "year": null,
            "url": "/models/porsche/911/magnus_walkers_1971_porsche_911_277.glb"
          }
        ]
      },
      {
        "id": "porsche-918-spyder",
        "name": "918 Spyder",
        "brandId": "porsche",
        "baseVariantId": "porsche-918-spyder--2015-mark-webber-porsche-918-spyder",
        "variants": [
          {
            "id": "porsche-918-spyder--2015-mark-webber-porsche-918-spyder",
            "name": "2015 Mark Webber Porsche 918 Spyder",
            "year": 2015,
            "url": "/models/porsche/918_Spyder/2015_mark_webber_porsche_918_spyder.glb"
          },
          {
            "id": "porsche-918-spyder--2015-porsche-918-spyder",
            "name": "2015 Porsche 918 Spyder",
            "year": 2015,
            "url": "/models/porsche/918_Spyder/2015_porsche_918_spyder.glb"
          },
          {
            "id": "porsche-918-spyder--2015-porsche-918-spyder-weissach-package-25",
            "name": "2015 Porsche 918 Spyder Weissach Package 25",
            "year": 2015,
            "url": "/models/porsche/918_Spyder/2015_porsche_918_spyder_weissach_package_25.glb"
          },
          {
            "id": "porsche-918-spyder--2015-porsche-918-spyder-weissach-package-3",
            "name": "2015 Porsche 918 Spyder Weissach Package 3",
            "year": 2015,
            "url": "/models/porsche/918_Spyder/2015_porsche_918_spyder_weissach_package_3.glb"
          },
          {
            "id": "porsche-918-spyder--2015-porsche-918-spyder-weissach-package-martini",
            "name": "2015 Porsche 918 Spyder Weissach Package Martini",
            "year": 2015,
            "url": "/models/porsche/918_Spyder/2015_porsche_918_spyder_weissach_package_martini.glb"
          }
        ]
      },
      {
        "id": "porsche-935",
        "name": "935",
        "brandId": "porsche",
        "baseVariantId": "porsche-935--2019-porsche-935-martini-racing",
        "variants": [
          {
            "id": "porsche-935--2019-porsche-935-martini-racing",
            "name": "2019 Porsche 935 Martini Racing",
            "year": 2019,
            "url": "/models/porsche/935/2019_porsche_935_martini_racing.glb"
          },
          {
            "id": "porsche-935--2019-porsche-935-salzburg-red-spare-package",
            "name": "2019 Porsche 935 Salzburg Red Spare Package",
            "year": 2019,
            "url": "/models/porsche/935/2019_porsche_935_salzburg_red_spare_package.glb"
          }
        ]
      },
      {
        "id": "porsche-959",
        "name": "959",
        "brandId": "porsche",
        "baseVariantId": "porsche-959--1988-porsche-959-bruce-canepa-upgrade",
        "variants": [
          {
            "id": "porsche-959--1988-porsche-959-bruce-canepa-upgrade",
            "name": "1988 Porsche 959 Bruce Canepa Upgrade",
            "year": 1988,
            "url": "/models/porsche/959/1988_porsche_959_bruce_canepa_upgrade.glb"
          }
        ]
      },
      {
        "id": "porsche-963",
        "name": "963",
        "brandId": "porsche",
        "baseVariantId": "porsche-963--2023-porsche-963-lmdh-racecar-no-5",
        "variants": [
          {
            "id": "porsche-963--2023-porsche-963-lmdh-racecar-no-5",
            "name": "2023 Porsche 963 LMDH Racecar No.5",
            "year": 2023,
            "url": "/models/porsche/963/2023_porsche_963_lmdh_racecar_no.5.glb"
          }
        ]
      },
      {
        "id": "porsche-carrera-gt",
        "name": "Carrera GT",
        "brandId": "porsche",
        "baseVariantId": "porsche-carrera-gt--2004-porsche-carrera-gt",
        "variants": [
          {
            "id": "porsche-carrera-gt--2004-porsche-carrera-gt-patrol",
            "name": "2004 Porsche Carrera GT Patrol",
            "year": 2004,
            "url": "/models/porsche/Carrera_GT/2004_porsche_carrera_gt-_patrol.glb"
          },
          {
            "id": "porsche-carrera-gt--2004-porsche-carrera-gt",
            "name": "2004 Porsche Carrera GT",
            "year": 2004,
            "url": "/models/porsche/Carrera_GT/2004_porsche_carrera_gt.glb"
          }
        ]
      },
      {
        "id": "porsche-cayenne",
        "name": "Cayenne",
        "brandId": "porsche",
        "baseVariantId": "porsche-cayenne--2009-porsche-cayenne-turbo-s",
        "variants": [
          {
            "id": "porsche-cayenne--2009-porsche-cayenne-turbo-s",
            "name": "2009 Porsche Cayenne Turbo S",
            "year": 2009,
            "url": "/models/porsche/Cayenne/2009_porsche_cayenne_turbo_s.glb"
          },
          {
            "id": "porsche-cayenne--2016-porsche-cayenne-turbo-s",
            "name": "2016 Porsche Cayenne Turbo S",
            "year": 2016,
            "url": "/models/porsche/Cayenne/2016_porsche_cayenne_turbo_s.glb"
          },
          {
            "id": "porsche-cayenne--2020-porsche-cayenne-turbo-coupe",
            "name": "2020 Porsche Cayenne Turbo Coupe",
            "year": 2020,
            "url": "/models/porsche/Cayenne/2020_porsche_cayenne_turbo_coupe.glb"
          },
          {
            "id": "porsche-cayenne--2022-porsche-cayenne-turbo-gt",
            "name": "2022 Porsche Cayenne Turbo GT",
            "year": 2022,
            "url": "/models/porsche/Cayenne/2022_porsche_cayenne_turbo_gt.glb"
          }
        ]
      },
      {
        "id": "porsche-macan",
        "name": "Macan",
        "brandId": "porsche",
        "baseVariantId": "porsche-macan--2019-porsche-macan-turbo",
        "variants": [
          {
            "id": "porsche-macan--2017-porsche-macan-gts",
            "name": "2017 Porsche Macan GTS",
            "year": 2017,
            "url": "/models/porsche/Macan/2017_porsche_macan_gts.glb"
          },
          {
            "id": "porsche-macan--2019-porsche-macan-turbo",
            "name": "2019 Porsche Macan Turbo",
            "year": 2019,
            "url": "/models/porsche/Macan/2019_porsche_macan_turbo.glb"
          }
        ]
      },
      {
        "id": "porsche-mission-r",
        "name": "Mission R",
        "brandId": "porsche",
        "baseVariantId": "porsche-mission-r--2021-porsche-mission-r-concept",
        "variants": [
          {
            "id": "porsche-mission-r--2021-porsche-mission-r-concept",
            "name": "2021 Porsche Mission R Concept",
            "year": 2021,
            "url": "/models/porsche/Mission_R/2021_porsche_mission_r_concept.glb"
          }
        ]
      },
      {
        "id": "porsche-panamera",
        "name": "Panamera",
        "brandId": "porsche",
        "baseVariantId": "porsche-panamera--2017-porsche-panamera-turbo",
        "variants": [
          {
            "id": "porsche-panamera--2017-porsche-panamera-turbo",
            "name": "2017 Porsche Panamera Turbo",
            "year": 2017,
            "url": "/models/porsche/Panamera/2017_porsche_panamera_turbo.glb"
          },
          {
            "id": "porsche-panamera--2021-porsche-panamera-turbo-s-sport-turismo",
            "name": "2021 Porsche Panamera Turbo S Sport Turismo",
            "year": 2021,
            "url": "/models/porsche/Panamera/2021_porsche_panamera_turbo_s_sport_turismo.glb"
          }
        ]
      },
      {
        "id": "porsche-taycan",
        "name": "Taycan",
        "brandId": "porsche",
        "baseVariantId": "porsche-taycan--2025-porsche-taycan-turbo-gt-weissach-package",
        "variants": [
          {
            "id": "porsche-taycan--2025-porsche-taycan-turbo-gt-weissach-package",
            "name": "2025 Porsche Taycan Turbo GT Weissach Package",
            "year": 2025,
            "url": "/models/porsche/Taycan/2025_porsche_taycan_turbo_gt_weissach_package.glb"
          }
        ]
      }
    ]
  },
  {
    "id": "toyota",
    "name": "Toyota",
    "models": [
      {
        "id": "toyota-supra-mk4",
        "name": "Supra MK4",
        "brandId": "toyota",
        "baseVariantId": "toyota-supra-mk4--supra-mk4",
        "variants": [
          {
            "id": "toyota-supra-mk4--supra-mk4",
            "name": "Supra MK4",
            "year": null,
            "url": "/models/toyota/supra-mk4.glb"
          }
        ]
      }
    ]
  }
];

/* ── Flat helpers ──────────────────────────────────────────────────── */

/** Every model across all brands. */
export const ALL_MODELS: CarModel[] = BRANDS.flatMap((b) => b.models);

/** Every variant across all models. */
export const ALL_VARIANTS: CarVariant[] = ALL_MODELS.flatMap((m) => m.variants);

/** Quick lookup by id. */
export const BRAND_MAP = new Map<string, Brand>(BRANDS.map((b) => [b.id, b]));
export const MODEL_MAP = new Map<string, CarModel>(ALL_MODELS.map((m) => [m.id, m]));
export const VARIANT_MAP = new Map<string, CarVariant>(
  ALL_VARIANTS.map((v) => [v.id, v])
);

/** The base variant of a model (falls back to the first variant). */
export function baseVariant(model: CarModel): CarVariant {
  return (
    model.variants.find((v) => v.id === model.baseVariantId) ?? model.variants[0]
  );
}

/* ── Legacy compat (flat Car type used by garage / quiz) ───────────── */

export type Car = {
  id: string;
  /** Model id (key into MODEL_MAP), e.g. "ferrari-f40". */
  modelId: string;
  /** Display name shown in the garage. */
  name: string;
  brand: string;
  /** Brand slug, e.g. "ferrari". */
  brandId: string;
  /** URL of the base variant GLB. */
  url: string;
  /** Scale reference — kept for the quiz; default 4.5 for auto-generated. */
  targetLength: number;
};

/**
 * One entry per **model** (not per variant), using the BASE variant's URL.
 * Used by the garage carousel and the quiz (base version only).
 */
export const CARS: Car[] = ALL_MODELS.map((m) => {
  const brand = BRAND_MAP.get(m.brandId)!;
  const base = baseVariant(m);
  return {
    id: m.id,
    modelId: m.id,
    name: `${brand.name} ${m.name}`,
    brand: brand.name,
    brandId: m.brandId,
    url: base.url,
    targetLength: 4.5,
  };
});
