// Sketchfab model mapping, keyed by **variant id** (see src/lib/cars.ts).
// Generated by scripts/sync-sketchfab.mjs from a Sketchfab collection.
// Museum embeds the `uid`; cards use `thumbnail`.

import ferrari from "./sketchfab/ferrari.json";

export type SketchfabModel = {
  /** Sketchfab model UID used to embed / link. */
  uid: string;
  /** CDN thumbnail URL (poster image) — may be null. */
  thumbnail: string | null;
  /** Sketchfab model title. */
  name: string;
  /** Author display name (attribution). */
  author: string | null;
  /** License slug, e.g. "by", "by-nc-sa". */
  license: string | null;
};

const MAP: Record<string, SketchfabModel> = {
  ...(ferrari as Record<string, SketchfabModel>),
};

/** Sketchfab model for a variant id, or undefined if not mapped. */
export function getSketchfab(variantId: string): SketchfabModel | undefined {
  return MAP[variantId];
}

/** Human-readable license label (fr). */
export function licenseLabel(slug: string | null): string {
  switch (slug) {
    case "by":
      return "CC BY";
    case "by-sa":
      return "CC BY-SA";
    case "by-nc":
      return "CC BY-NC";
    case "by-nc-sa":
      return "CC BY-NC-SA";
    case "by-nd":
      return "CC BY-ND";
    case "by-nc-nd":
      return "CC BY-NC-ND";
    case "cc0":
      return "CC0";
    default:
      return slug ?? "—";
  }
}
